#! /usr/bin/env bash

SCRIPTS_PATH="$QUICKTEST_PATH"/scripts

desired_bash_version=4
bash_version="$( "$QTBASH" -c 'echo -n $BASH_VERSINFO' )"

if [ "$bash_version" -lt "$desired_bash_version" ]
then
	>&2 printf "%s\n"                                              \
	    "Desired bash version = $desired_bash_version"             \
	    "Found $bash_version"                                      \
	    "export QTBASH env var to bashv$desired_bash_version path"
	exit 1
fi

"$QTBASH" "$SCRIPTS_PATH"/quicktest "$@"
