#! /usr/bin/env bash

set -e
source "$CLIUM_SOURCE_PATH"/error_handler
source "$CLIUM_SOURCE_PATH"/constants
source "$CLIUM_SOURCE_PATH"/utility_funcs
source "$CLIUM_SOURCE_PATH"/data_interface
source "$CLIUM_SOURCE_PATH"/option_parser
source "$CLIUM_SOURCE_PATH"/common_options
set +e

print_usage() {
	printf_err "%s\n"                                  \
	'clium action [<key_for_action>]'                  \
	'    [-a|--add-action <action_name> <action_key>]' \
	'    [--config-file]'                              \
	'    [-d|--delete <action_name>]'                  \
	'    [-h|--help]'                                  \
	'    [-r|--rename [<old_name>] <new_name>]'        \
	'    [-s|--show-all]'
}

parse_action_options() {
	local option_parser_retval

	parse_options \
		'action'                 '...'                   \
		\
		'-a' , '--add-action'    '1 1'                   \
		'--config-file'          '0'                     \
		'-d' , '--delete'        '...'                   \
		'-h' , '--help'          '0'                     \
		'-r' , '--rename'        '1 -1'                  \
		'-s' , '--show-all'      '0'                     \
		                                                 \
		';'                                              \
		"$@"

	option_parser_retval=$?

	if [ $option_parser_retval -ne 0 ] ; then
		option_parser_error_msg $option_parser_retval
		print_usage
		return_error
	fi
}

self_actions() {
	local action_key
	local action
	local action_args

	action_key=${ARGS[action,0]}

	action="$( get_from_user_config_file "$action_key" )" || return_error

	action="$( fpreprocess <<<"$action" )" || return_error

	action_args="$(forward_args 'action' '1')" || return_error

	"$CLIUM_BASH" -c "$action $action_args"
}

option_add_action() {
	local action_name
	local action_key
	local new_action_path
	local contents

	action_name=${ARGS[-a,0]}
	action_key=${ARGS[-a,1]}

	new_action_path="$USER_COMMANDS_DIR/$action_name"

	prompt_if_overwrite "$new_action_path" || return_error

	touch "$new_action_path" || return_error

	contents="$( < $USER_COMMAND_TEMPLATE )"

	replace                    \
		"$ACTION_KEY_REPLACEE" \
		"$action_key"          \
		"$contents"            \
		> "$new_action_path"   \
		|| return_error

	chmod u=rwx,go-rwx "$new_action_path" || {
		rm -f "$new_action_path"
		return_error
	}

	echo "Added action $action_name."
	echo "This action will run the code given by key $action_key in your user config_file"
}

option_delete() {
	delete_files "$USER_COMMANDS_DIR" "SELECT ACTION(-d)" || return_error
}

option_rename() {
	rename_file "$USER_COMMANDS_DIR" || return_error
}

option_show_all() {
	list_time_sorted "$USER_COMMANDS_DIR" || return_error
}

action() {
	local default_options

	if [ -z "$*" ]
	then
		default_options="$( get_default_args )" || return_error
		eval set -- $default_options
	fi

	parse_action_options "$@" || return_error

	if [ "${ARG_CNT[action]:-0}" -ne 0 ]
	then
		self_actions || return_error
		return 0
	fi

	for option in "${!OPTIONS[@]}"
	do
		case "$option" in
			-a|--add-action)
				option_add_action || return_error
				;;
			--config-file)
				option_config_file || return_error
				;;
			-d)
				option_delete || return_error
				;;
			-h)
				option_help
				;;
			-r)
				option_rename || return_error
				;;
			-s)
				option_show_all || return_error
				;;
		esac
	done

	return 0
}

action "$@"
