#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/"common

set -e
source "$COMMON_PATH"/error_handler
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/utility_funcs
source "$DATA_INTERFACE_DIR"/utility_funcs

source "$SCRIPTS_DIR"/option_parser
source "$SUB_COMMANDS_DIR"/common
set +e

print_usage() {

	printf_err "%s\n"                                  \
	'quicktest user_config'                            \
	'    [-c|--current]'                               \
	'    [-d|--delete <user_config_file_name>]'        \
	'    [-h|--help]'                                  \
	'    [-m|--modify [<user_config_file_name>]]'      \
	'    [-n|--new <user_config_file_name>]'           \
	'    [-p|--path]'                                  \
	'    [-s|--show-all]'

}

parse_user_config_options() {

	local option_parser_retval

	parse_options \
		, 'OPTIONS' 'ARG_CNT' 'ARGS' 'self' '0' ';' '--'     \
		                                                     \
		'-c' , '--current'                '0'                \
		'-d' , '--delete'                 '-1'               \
		'-h' , '--help'                   '0'                \
		'-m' , '--modify'                 '-1'               \
		'-n' , '--new'                    '1'                \
		'-p' , '--path'                   '0'                \
		'-s' , '--show-all'               '0'                \
		                                                     \
		';'                                                  \
		"$@"

	option_parser_retval=$?

	if [ $option_parser_retval -ne 0 ] ; then
		option_parser_error_msg $option_parser_retval 'OPTIONS'
		print_usage
		return_error
	fi

}

option_current() {
	local user_config

	user_config="$(get_from_current_defaults "$USER_CONFIG_FILE_KEY")" || return_error

	printf "%s\n" "$user_config"
}

option_delete() {
	delete_files "$USER_CONFIG_FILES_DIR" "SELECT USER CONFIG(-d)" || return_error
}

option_modify() {
	local user_config_full_path
	local user_config

	user_config=${ARGS[-m,0]}

	if [ ${ARG_CNT[-m]:-0} -eq 1 ]
	then
		user_config=${ARGS[-m,0]}
	else
		user_config="$( fzf_search "SELECT USER CONFIG(-u)" "$USER_CONFIG_FILES_DIR" )"
		[ -z "$user_config" ] && return_error
	fi

	user_config_full_path="$USER_CONFIG_FILES_DIR/$user_config"

	print_if_not_file "$user_config_full_path" && return_error

	open_file "$user_config_full_path" || return_error
}

option_new() {
	local user_config
	local user_config_full_path

	user_config=${ARGS[-n,0]}
	user_config_full_path="$USER_CONFIG_FILES_DIR/$user_config"

	exists_but_not_file "$user_config_full_path" && return_error

	open_file "$user_config_full_path" || return_error
}

option_path() {
	printf "%s\n" "$(current_user_config_path)"
}

option_show_all() {
	list_time_sorted "$USER_CONFIG_FILES_DIR" || return_error
}

user_config() {

	parse_user_config_options "$@" || return_error

	for option in "${!OPTIONS[@]}"
	do
		case "$option" in
			-c)
				option_current || return_error
				;;
			-d)
				option_delete || return_error
				;;
			-h)
				option_help || return_error
				;;
			-m)
				option_modify || return_error
				;;
			-n)
				option_new || return_error
				;;
			-p)
				option_path || return_error
				;;
			-s)
				option_show_all || return_error
				;;
		esac
	done

	return 0
}

user_config "$@"
