#! /usr/bin/env bash

set -e
source "$QT_COMMON_PATH"/constants
source "$QT_COMMON_PATH"/error_handler
source "$QT_COMMON_PATH"/data_interface
set +e

# quicktest vars:
#
#  FILE_TO_OPEN
#      Represents the file that is going to get opened as per the current_defaults.
#      This can be file opened for modifying a user config, an instance etc.
#
#  INSTANCE
#      Current instance name
#
#  INSTANCES_DIR
#      Directory where instances are stored
#
#  OUTPUT_DIR
#      A separate directory dedicated to store output files.
#
#  QUICKTEST_PATH
#      Path where quicktest is installed.
#
VAR() {
	local var="$1" ; shift
	local value

	case "$var" in
		'FILE_TO_OPEN')
			value="$( get_from_current_defaults "FILE_TO_OPEN" )" || return_error
			;;
		'INSTANCE')
			value="$( get_from_current_defaults "INSTANCE" )" || return_error
			;;
		'INSTANCES_DIR')
			value=$INSTANCES_DIR
			;;
		'OUTPUT_DIR')
			value=$OUTPUT_DIR
			;;
		'QUICKTEST_PATH')
			value="$QUICKTEST_PATH"
			;;
	esac

	printf "%s" "$value"
}

VAR "$@"
