#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
set +e


# quicktest vars:
#
#  ___FILE_TO_OPEN___
#      -> Represents the file that is going to get opened as per the current_defaults.
#
#  ___INSTANCE___
#      -> Current instance name
#
#  ___QUICKTEST_PATH___
#      -> Path where quicktest is installed.
#
get_quicktest_var_value() {
	local var="$1" ; shift

	#
	# This function is called from awk's subshell.
	# Variables or functions used here should be exported
	# to subshell.
	#

	local value

	case "$var" in
		'___FILE_TO_OPEN___')
			value="$( get_value_for_key "$CURRENT_DEFAULTS_FILE" "FILE_TO_OPEN" )"
			;;
		'___INSTANCE___')
			value="$( get_value_for_key "$CURRENT_DEFAULTS_FILE" "INSTANCE" )"
			;;
		'___QUICKTEST_PATH___')
			value="$QUICKTEST_PATH"
			;;
	esac

	return_if_error

	echo -n "$value"
}

get_quicktest_var_value "$@"
