#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/src/scripts/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
set +e

#
# Same as get_value_for_key but param(file)
# gets defaulted to current_defaults file
#
get_from_current_defaults() {

	local key="$1" ; shift

	get_value_for_key "$CURRENT_DEFAULTS_FILE" "$key" || return_error
}

get_from_current_defaults "$@"
