#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler

#
# Same as get_value_for_key but param(file)
# gets defaulted to current_defaults file
#
get_from_current_defaults() {

	local key="$1" ; shift
	local value

	value="$(
		get_value_for_key "$CURRENT_DEFAULTS_FILE" "$key"
	)"

	return_if_error

	value="$(
		replace_quicktest_vars "$value"
	)"

	return_if_error

	echo -n "$value"
}

get_from_current_defaults "$@"
