#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
source "$COMMON_PATH"/utility_funcs
set +e

#
# Prints the value of the key on stdout
#
# param1:
#  quicktest config file path
#
# param2:
#  Key to get
#
get_value_for_key() {
	local file=$1; shift
	local key=$1 ; shift

	[ -z "$file" ] && a_echo_err "param(file) is null" && return 1
	[ -z "$key" ]  && a_echo_err "param(key) is null" && return 1

	print_if_not_file "$file" && return 1

	local old_val=$key
	key="$( first_word "$key" )"

	if [ "$old_val" != "$key" ]
	then
		a_echo_err "key cannot contain spaces"
		return 1
	fi

	awk -v key="$key" -f "$AWK_FILES_PATH/get_value_for_key.awk" "$file"
}

get_value_for_key "$@"
