#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
source "$COMMON_PATH"/utility_funcs
set +e

#
# Description:
#  Removes the first occurence of key given by param1.
#
# param1:
#  file path
#
# param2:
#  Key to remove
#
remove_key() {

	local file="$1" ; shift
	local key="$1" ; shift

	[ -z "$file" ] && a_echo_err "param(file) is null" && return 1
	[ -z "$key" ]  && a_echo_err "param(key) is null" && return 1

	print_if_not_file "$file" && return 1

	local temp_file="$(mktemp "/tmp/quicktest.temp.XXXXX")"

	local old_val=$key
	key="$( first_word "$key" )"

	if [ "$old_val" != "$key" ]
	then
		a_echo_err "key cannot contain spaces"
		return 1
	fi

	awk \
		-v key="$key" \
		-f "$AWK_FILES_PATH/remove_key.awk" \
		"$file" > "$temp_file"

	if [ $? -ne 0 ] ; then
		rm "$temp_file" 2> /dev/null
		a_echo_err "${FUNCNAME[0]}() failed"
		return 1
	fi

	mv "$temp_file" "$file"

}

remove_key "$@"
