#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
set +e

#
# Description:
#  Replaces quicktest vars with there appropriate values.
#
# param1:
#  Input on which replacements will be performed.
#
replace_quicktest_vars() {

	local input="$1"
	local updated_input

	declare -a QUICKTEST_VARS

	QUICKTEST_VARS=(
		'___FILE_TO_OPEN___'
		'___INSTANCE___'
		'___QUICKTEST_PATH___'
	)

	updated_input="$(
		awk \
		-v GET_QUICKTEST_VAR_VALUE="$DATA_INTERFACE_DIR/get_quicktest_var_value" \
		-v QTBASH="$QTBASH" \
		-v BASH_QUICKTEST_VARS="${QUICKTEST_VARS[*]}" \
		-f "$AWK_FILES_PATH/quicktest_var_replaces.awk" <<<"$input"
	)"

	return_if_error

	printf "%s" "$updated_input"
}

replace_quicktest_vars "$@"
