#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
set +e

#
# Same as set_value_for_key but param(file)
# gets defaulted to file given by key CURRENT_USER_CONFIG_FILE
# in current_defaults file
#
set_in_user_config_file() {
	local key="$1" ; shift
	local value="$1" ; shift
	local user_config_file_name
	local user_config_file_path

	user_config_file_name="$( get_from_current_defaults "$USER_CONFIG_FILE_KEY" )"

	if [ $? -eq 0 ]
	then
		print_if_key_is_null "$USER_CONFIG_FILE_KEY" "$user_config_file_name" && return 1
		user_config_file_path="$USER_CONFIG_FILES_DIR/$user_config_file_name"
	else
		user_config_file_path="$DEFAULT_USER_CONFIG_FILE"
	fi

	set_value_for_key "$user_config_file_path" "$key" "$value" || return_error
}

set_in_user_config_file "$@"
