#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/"src/scripts/common

set -e
source "$COMMON_PATH"/error_handler
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/utility_funcs
source "$COMMON_PATH"/data_interface
source "$COMMON_PATH"/option_parser
source "$SUB_COMMANDS_DIR"/common_options
set +e

print_usage() {

	printf_err "%s\n"                             \
	'quicktest open'                              \
	'    [relative_count [-g|--global]]'          \
	'    [-b|--boilerplate [<boilerplate_name>]]' \
	'    [--config-file]'                         \
	'    [-h|--help]'                             \
	'    [-i|--instance [<instance_name>]]'       \
	'    [-n|--new]'                              \
	'    [-u|--user-config [<user_config_name>]]'

}

parse_open_options() {

	local option_parser_retval

	parse_options \
		'open'                   '-1'                    \
		\
		'-b' , '--boilerplate'   '-1'                    \
		'--config-file'          '0'                     \
		'-h' , '--help'          '0'                     \
		'-i' , '--instance'      '-1'                    \
		'-n' , '--new'           '0'                     \
		'-u' , '--user-config'   '-1'                    \
		                                                 \
		';'                                              \
		"$@"

	option_parser_retval=$?

	if [ $option_parser_retval -ne 0 ] ; then
		option_parser_error_msg $option_parser_retval
		print_usage
		return_error
	fi

}

option_boilerplate() {
	local boilerplate_full_path

	boilerplate_full_path="$( arg_or_fzf_search "$BOILERPLATE_FILES_DIR" "SELECT BOILERPLATE(-b):" '-b' )" \
		|| return_error

	touch "$boilerplate_full_path" || return_error

	printf "%s" "$boilerplate_full_path"
}

option_user_config() {
	local user_config
	local user_config_full_path

	if [ ${ARG_CNT[-u]:-0} -eq 1 ]
	then
		user_config=${ARGS[-u,0]}
	else
		user_config="$( fzf_search "SELECT USER CONFIG(-u)" "$USER_CONFIG_FILES_DIR" )" || return_error
		[ -z "$user_config" ] && return_error
	fi

	user_config_full_path="$USER_CONFIG_FILES_DIR/$user_config"
	print_if_not_file "$user_config_full_path" && return_error

	set_in_current_defaults "$USER_CONFIG_FILE_KEY" "$user_config" || return_error

	touch "$user_config_full_path"

	printf "%s" "$user_config_full_path"
}

#
# Description:
#   Would check if ARGS[-i,?] contains anything. If not would
#   provide user a fzf search menu to search for the desired instance.
#   If the instance doesn't exist, it would be created with all directories
#   in between.
#   At the end, intance's full path would be echoed.
#
option_instance() {
	local instance
	local instance_full_path

	if [ ${ARG_CNT[-i]:-0} -eq 1 ]
	then
		instance=${ARGS[-i,0]}
	else
		instance="$( fzf_search "SELECT INSTANCE(-i):" "$INSTANCES_DIR" )" || return_error
		[ -z "$instance" ] && return_error
	fi

	instance_full_path="$INSTANCES_DIR/$instance"

	exists_but_not_file "$instance_full_path" && return_error

	set_in_current_defaults "$INSTANCE_KEY" "$instance" || return_error

	local dir="$( dirname "$file" )"
	mkdir -p "$dir"

	touch "$instance_full_path"

	printf "%s" "$instance_full_path"
}

instance_by_relative_cnt() {
	local instance
	local instance_full_path

	instance="$( get_by_relative_cnt "$INSTANCES_DIR" "${ARGS[open,0]}")" || return_error

	instance_full_path="$INSTANCES_DIR/$instance"

	exists_but_not_file "$instance_full_path" && return_error

	set_in_current_defaults "$INSTANCE_KEY" "$instance" || return_error

	touch "$instance_full_path"

	printf "%s" "$instance_full_path"
}

option_help() {
	less "$( dirname $BASH_SOURCE )/help.txt"
}

write_boilerplate_to_instance() {
	local boilerplate_path=$1 ; shift
	local instance_path=$1 ; shift

	prompt_if_overwrite "$instance_path" || return_error

	fpreprocess < "$boilerplate_path" > "$instance_path" || return_error
}

open() {
	local boilerplate_full_path
	local user_config_full_path
	local instance_full_path
	local default_options

	if [ -z "$*" ]
	then
		default_options="$( get_default_args )" || return_error
		eval set -- $default_options
	fi

	parse_open_options "$@" || return_error

	if [ -n "${OPTIONS[-h]}" ]
	then
		option_help
		return 0
	fi

	if [ -n "${OPTIONS[--config-file]}" ]
	then
		option_config_file || return_error
		return 0
	fi

	if [ -n "${OPTIONS[-u]}" ]
	then
		user_config_full_path="$(option_user_config)" || return_error
	else
		user_config_full_path="$(current_user_config_path)" || return_error
	fi

	if [ -n "${OPTIONS[-i]}" ]
	then
		instance_full_path="$(option_instance)" || return_error
	else
		if [ -n "${ARGS[open,0]}" ]
		then
			instance_full_path="$(instance_by_relative_cnt)" || return_error
		else
			instance_full_path="$(current_instance_path)" || return_error
		fi
	fi

	if [ -n "${OPTIONS[-n]}" ]
	then
		if [ -n "${OPTIONS[-b]}" ]
		then
			boilerplate_full_path="$(option_boilerplate)" || return_error
		else
			boilerplate_full_path="$(current_boilerplate_path)" || return_error
		fi

		write_boilerplate_to_instance "$boilerplate_full_path" "$instance_full_path" || return_error
	fi

	open_file "$instance_full_path" || return_error

	return 0
}

open "$@"
