#! /usr/bin/env bash

[ -n "$__KEYS__" ] && return 0
readonly __KEYS__=1

# >>> current defaults keys

# this key is set to the file which is gonna get
# opened
readonly FILE_TO_OPEN_KEY='FILE_TO_OPEN'

# this key is set to the current instance name
readonly INSTANCE_KEY='INSTANCE'

# this key is set to the current user config file
readonly USER_CONFIG_FILE_KEY='USER_CONFIG_FILE'



# >>> user config file keys

# this is used in user config files to
# tell how the editor needs to be opened.
readonly HOW_TO_OPEN_EDITOR_KEY='HOW_TO_OPEN_EDITOR'

# this keys holds a boilerplate denoting the boilerplate
# file to be used when --new option is supplied to `lt open`
readonly BOILERPLATE_KEY='BOILERPLATE'

# this keys holds a boilerplate denoting the boilerplate
# project to be used when --new option is supplied to `lt project`
readonly PROJECT_BOILERPLATE_KEY='BOILERPLATE_PROJECT'



# >>> command config file keys

# this is used in command config files for default args
# to be used with command when no args supplied
readonly DEFAULT_ARGS_KEY='DEFAULT_ARGS'
