#! /usr/bin/env bash

[ -n "$__USER_FILES__" ] && return 0
readonly __USER_FILES__=1

# global aliases created by user are stored here
readonly ALIAS_FILE_PATH="$USER_DATA_DIR/alias_file.qtc"

# user can rename the funcs in rename file globally
readonly RENAME_FILE_PATH="$USER_DATA_DIR/rename_file.qtc"


# user config inference from file extensions uses this file
readonly EXTENSION_MAP_FILE_PATH="$USER_DATA_DIR/extension_map.qtc"
