#! /usr/bin/env bash

[ -n "$__USER_DIRS__" ] && return 0
readonly __USER_DIRS__=1

# for storing user defined funcs
readonly USER_FUNC_DIR="$USER_DATA_DIR/func"

# user defined funcs use FUNC_DUMP_DIR to store their data
readonly FUNC_DUMP_DIR="$USER_DATA_DIR/func_dump_dir"


# user config files defined by user are stored here
readonly USER_CONFIG_FILES_DIR="$USER_DATA_DIR/user_config_files"

# boilerplate files made by user are stored here
readonly BOILERPLATE_FILES_DIR="$USER_DATA_DIR/boilerplates"

# boilerplate projects made by user are stored here
readonly PROJECT_BOILERPLATE_DIR="$USER_DATA_DIR/project_boilerplates"

# this stores current defaults files for all tty instances
readonly CURRENT_DEFAULTS_DIR="$USER_DATA_DIR/current_defaults"

# instances made by user are stored here.
readonly INSTANCES_DIR="$USER_DATA_DIR/instances"

# projects made by user are stored here.
readonly PROJECTS_DIR="$USER_DATA_DIR/projects"


# this is an optional output directory which user can use
# for generated executable files. e.g., gcc generated a.out can be
# stored here.
readonly OUTPUT_DIR="$USER_DATA_DIR/outputs"


# commands defined by the user by `lt action` are stored here.
readonly USER_COMMANDS_DIR="$COMMANDS_DIR/user_commands"
