#! /usr/bin/env bash

# don't source the script twice
[ -n "$__CONSTANTS__" ] && return 0
readonly __CONSTANTS__=1

readonly QUICKTEST_CONFIG_FILE="$QUICKTEST_PATH/quicktest.config"

readonly SCRIPTS_DIR="$QUICKTEST_PATH/scripts"
readonly DATA_INTERFACE_DIR="$QUICKTEST_PATH/data_interface"
readonly AWK_FILES_PATH="$DATA_INTERFACE_DIR/awk"
readonly DATA_DIR="$QUICKTEST_PATH/data"
readonly COMMON_DIR="$QUICKTEST_PATH/common"
readonly COMMANDS_DIR="$QUICKTEST_PATH/commands"

PATH="$DATA_INTERFACE_DIR:$PATH"

readonly USER_DATA_DIR="$DATA_DIR/user_data"
readonly PROGRAM_DATA_DIR="$DATA_DIR/program_data"

readonly PROGRAM_FUNC_DIR="$PROGRAM_DATA_DIR/func"
readonly USER_FUNC_DIR="$USER_DATA_DIR/func"
readonly FUNC_TEMPLATE="$PROGRAM_DATA_DIR/func_template"

readonly USER_CONFIG_FILES_DIR="$USER_DATA_DIR/user_config_files"
readonly BOILERPLATE_FILES_DIR="$USER_DATA_DIR/boilerplates"
readonly CURRENT_DEFAULTS_FILE="$USER_DATA_DIR/current_defaults"

readonly USER_COMMAND_TEMPLATE="$PROGRAM_DATA_DIR/user_command_template"

readonly INSTANCES_DIR="$USER_DATA_DIR/instances"
readonly TEST_DIR="$INSTANCES_DIR/test"

readonly OUTPUT_DIR="$USER_DATA_DIR/outputs"

readonly USER_COMMANDS_DIR="$COMMANDS_DIR/user_commands"
readonly PROGRAM_COMMANDS_DIR="$COMMANDS_DIR/program_commands"

readonly FILE_TO_OPEN_KEY='FILE_TO_OPEN'
readonly HOW_TO_OPEN_EDITOR_KEY='HOW_TO_OPEN_EDITOR'
readonly INSTANCE_KEY='INSTANCE'
readonly USER_CONFIG_FILE_KEY='USER_CONFIG_FILE'
readonly BOILERPLATE_KEY='BOILERPLATE'
readonly DEFAULT_ARGS_KEY='DEFAULT_ARGS'
readonly ACTION_KEY_REPLACEE='___ACTION_KEY___'

readonly RED='\033[0;31m'
readonly DEFAULT_COLOR='\033[0m'

readonly BOLD="$(tput bold)"
readonly OFF_BOLD="$(tput sgr0)"
