#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/common"

source "$COMMON_PATH"/error_handler

print_if_key_is_null() {
	if [ -z "$2" ]
	then
		a_printf_err "key $1 is empty"
		return 0
	fi

	return 1
}

print_if_not_file() {
	if [ ! -f "$1" ]
	then
		a_printf_err "$1 : No such file"
		return 0
	fi

	return 1
}

exists_but_not_file() {
	if [ ! -f "$1" ] && [ -e "$1" ]
	then
		a_printf_err "$1 exists but isn't a file"
		return 0
	fi

	return 1
}

# trims leading and trailing spaces
# also if more than one blank exists, it trims it to single blank
trim_blanks() {
	awk '{$1=$1}1' <<<"$1"
}

trim_leading_and_trailing_blanks() {

	awk '{
		# trim leading spaces
		sub(/^ +/, "", $0)
		sub(/^\t+/, "", $0)

		# trim trailing spaces
		sub(/ +$/, "", $0)
		sub(/\t+$/, "", $0)
	}1' <<<"$1"
}

first_word() {
	awk '{print $1}' <<<"$1"
}
