#! /usr/bin/env bash

# don't source the script twice
[ -n "$__CONSTANTS__" ] && return 0
readonly __CONSTANTS__=1

readonly PROG_NAME='clium'

# >>> main clium directories
readonly SRC_DIR="$CLIUM_PATH/src"
readonly DATA_DIR="$CLIUM_PATH/data"
readonly COMMANDS_DIR="$CLIUM_PATH/commands"

readonly UTILS_DIR="$SRC_DIR/utils"
readonly UTILS_BIN_DIR="$UTILS_DIR/bin"
readonly UTILS_LIBS_DIR="$UTILS_DIR/libs"
readonly SUB_COMMANDS_DIR="$SRC_DIR/sub_commands"

readonly USER_DATA_DIR="$DATA_DIR/user_data"
readonly PROGRAM_DATA_DIR="$DATA_DIR/program_data"

readonly CONSTANTS_DIR="$SRC_DIR/source/_constants"

source "$CONSTANTS_DIR/keys"
source "$CONSTANTS_DIR/paths"
source "$CONSTANTS_DIR/program_dirs"
source "$CONSTANTS_DIR/program_files"
source "$CONSTANTS_DIR/replacees"
source "$CONSTANTS_DIR/text_formatters"
source "$CONSTANTS_DIR/user_dirs"
source "$CONSTANTS_DIR/user_files"
