#! /usr/bin/env bash

[ -n "$__SUB_COMMANDS_COMMON__" ] && return 0
readonly __SUB_COMMANDS_COMMON__=1

option_help() {
	less "$( dirname $0 )/help.txt"
}

get_by_relative_cnt() {
	local dir=$1; shift
	local cnt=$1

	if [ -z "$cnt" ]
	then
		cnt=${ARGS[self,0]}
	fi

	if ! is_num "$cnt"
    then
        a_echo_err "$cnt: invalid relative count"
        return_error
    fi

	list_time_sorted_null_term "$dir" | gawk -v line="$cnt" '
		BEGIN {
			RS="\0"
		}
		NR == line {
			print
		}
	' || return_error
}
