#! /usr/bin/env bash

COMMON_PATH="$QUICKTEST_PATH/src/scripts/common"

set -e
source "$COMMON_PATH"/constants
source "$COMMON_PATH"/error_handler
source "$COMMON_PATH"/option_parser
set +e

___FUNC_NAME___() {

}

___FUNC_NAME___ "$@"
